CREATE TABLE IF NOT EXISTS `Vacations` (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title VARCHAR(128) NOT NULL,
    bodyText VARCHAR(512) NOT NULL,
    pictureURL VARCHAR(256) NOT NULL,
    maxUsers INTEGER NOT NULL,
    userCount INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS `Users` (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(64) NOT NULL,
    telephone VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS `Reservations` (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    userid INTEGER NOT NULL,
    vacationid INTEGER NOT NULL,
    active BOOLEAN NOT NULL,
    requestcancellation BOOLEAN NOT NULL
    FOREIGN KEY (vacationid) REFERENCES Vacations(id)
    FOREIGN KEY (userid) REFERENCES Users(id)
);